version: '3'
services:
  database1:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    volumes:
      - datauser:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    restart: always
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
    ports:
      - 8081:8080
    command: >
      start -dev

volumes:
  datauser:
    driver: local