spring:
  application:
    name: learning_managment_system_dev
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/hamza
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: lms-auth
      principle-attribute: preferred_username

keycloak:
  realm: hamza
  server-url: http://localhost:8081
  client-id: lms-auth
  admin:
    username: admin
    password: admin

server:
  port: 8082


